### ISSUE TITLE
Difference to flosse/npm-source-sans-pro

### ISSUE THREAD

**Issue by bernhardreiter** [dasrick/npm-font-source-sans-pro#2]
For readers it would be helpful if there was a link to similiar efforts and a short mention of the differences, see https://github.com/flosse/npm-source-sans-pro/issues/1.

Thanks!

**Comment by dasrick** [comment]
It looks like the following are the differences

* dasrick-version use a newer version of the font (2.020R-ro/1.075R-it (release date: 2015-09-16))
* dasrick-version supports CSS as well ass LESS and SCSS 

Thats it ...
